import { MenuItem } from "../../../types";

const menuItems: MenuItem[] = [
      // Starters (Meat)
  {
    id: '1',
    name: 'Beef Carpaccio',
    description: 'Thinly sliced raw beef with arugula, Parmesan, capers, and truffle oil drizzle',
    price: 2000,
    category: 'starters',
    subcategory: 'meat',
    image: '/public/assets/menu/Beef_Carpaccio.jpg',
    available: true,
    eta: 45,
  },
  {
    id: '2',
    name: 'Charcuterie Board',
    description: 'Selection of cured meats with pickles, olives, and artisanal bread',
    price: 2200,
    category: 'starters',
    subcategory: 'meat',
    image: '/public/assets/menu/Charcuterie_Board.jpg',
    available: true,
    eta: 30,
  },
  {
    id: '3',
    name: 'Chicken Liver Pate',
    description: 'Smooth chicken liver pâté served with toasted brioche and fruit chutney',
    price: 1800,
    category: 'starters',
    subcategory: 'meat',
    image: '/public/assets/menu/Chicken_Liver_Pate.jpg',
    available: true,
    eta: 60,
  },
  {
    id: '4',
    name: 'Duck Rillettes',
    description: 'Shredded duck confit served with toasted brioche and fruit chutney',
    price: 1800,
    category: 'starters',
    subcategory: 'meat',
    image: '/public/assets/menu/Duck_Rillettes.jpg',
    available: true,
    eta: 25,
  },
  {
    id: '5',
    name: 'Lamb Meatballs',
    description: 'Juicy lamb meatballs served with mint yogurt dipping sauce',
    price: 2000,
    category: 'starters',
    subcategory: 'meat',
    image: '/public/assets/menu/Lamb_Meatballs.jpg',
    available: true,
    eta: 50,
  },
  {
    id: '6',
    name: 'Mini Wagyu Sliders',
    description: 'Wagyu beef sliders with caramelized onions and gourmet aioli',
    price: 2100,
    category: 'starters',
    subcategory: 'meat',
    image: '/public/assets/menu/Mini_Wagyu_Sliders.jpg',
    available: true,
    eta: 75,
  },
  {
    id: '7',
    name: 'Pork Belly Bites',
    description: 'Crispy pork belly with tangy BBQ sauce',
    price: 1700,
    category: 'starters',
    subcategory: 'meat',
    image: '/public/assets/menu/Pork_Belly_Bites.jpg',
    available: true,
    eta: 40,
  },
  {
    id: '8',
    name: 'Spicy Korean BBQ Wings',
    description: 'Juicy chicken wings coated with spicy Korean BBQ sauce',
    price: 1800,
    category: 'starters',
    subcategory: 'meat',
    image: '/public/assets/menu/Spicy_Korean_BBQ_Wings.jpg',
    available: true,
    eta: 90,
  },
  {
    id: '9',
    name: 'Steak Tartare',
    description: 'Raw beef with capers, shallots, and quail egg, served with crispy toast',
    price: 2200,
    category: 'starters',
    subcategory: 'meat',
    image: '/public/assets/menu/Steak_Tartare.jpg',
    available: true,
    eta: 35,
  },

  // Starters (Seafood)
  {
    id: '10',
    name: 'Clam Chowder',
    description: 'Creamy soup with tender clams, potatoes, and a hint of bacon',
    price: 1500,
    category: 'starters',
    subcategory: 'seafood',
    image: '/public/assets/menu/Clam_Chowder.jpg',
    available: true,
    eta: 55,
  },
  {
    id: '11',
    name: 'Crab Cakes',
    description: 'Crispy crab cakes served with zesty aioli dipping sauce',
    price: 1800,
    category: 'starters',
    subcategory: 'seafood',
    image: '/public/assets/menu/Crab_Cakes.jpg',
    available: true,
    eta: 70,
  },
  {
    id: '12',
    name: 'Grilled Octopus',
    description: 'Tender grilled octopus served with lemon and herbs',
    price: 2200,
    category: 'starters',
    subcategory: 'seafood',
    image: '/public/assets/menu/Grilled_Octopus.jpg',
    available: true,
    eta: 50,
  },
  {
    id: '13',
    name: 'Lobster Bisque',
    description: 'Velvety soup with lobster chunks, garnished with fresh chives',
    price: 1800,
    category: 'starters',
    subcategory: 'seafood',
    image: '/public/assets/menu/Lobster_Bisque.jpg',
    available: true,
    eta: 85,
  },
  {
    id: '14',
    name: 'Oysters Rockefeller',
    description: 'Baked oysters with butter sauce, herbs, and breadcrumbs',
    price: 2500,
    category: 'starters',
    subcategory: 'seafood',
    image: '/public/assets/menu/Oyster_Rockefeller.jpg',
    available: true,
    eta: 95,
  },
  {
    id: '15',
    name: 'Scallop Ceviche',
    description: 'Fresh scallops marinated in citrus juices with onions, cilantro, and chili',
    price: 2000,
    category: 'starters',
    subcategory: 'seafood',
    image: '/public/assets/menu/Scallop_Ceviche.jpg',
    available: true,
    eta: 65,
  },
  {
    id: '16',
    name: 'Shrimp Cocktail',
    description: 'Chilled shrimp served with tangy cocktail sauce and lemon wedge',
    price: 1600,
    category: 'starters',
    subcategory: 'seafood',
    image: '/public/assets/menu/Shrimp_Cocktail.jpg',
    available: true,
    eta: 35,
  },
  {
    id: '17',
    name: 'Smoked Salmon Crostini',
    description: 'Smoked salmon on crispy crostini with cream cheese and dill',
    price: 1800,
    category: 'starters',
    subcategory: 'seafood',
    image: '/public/assets/menu/Smoked_Salmon_Crostini.jpg',
    available: true,
    eta: 20,
  },
  {
    id: '18',
    name: 'Tuna Tartare',
    description: 'Fresh tuna with avocado, soy sauce, sesame oil, and wonton crisps',
    price: 2200,
    category: 'starters',
    subcategory: 'seafood',
    image: '/public/assets/menu/Tuna_Tartare.jpg',
    available: true,
    eta: 80,
  },

  // Starters (Vegetarian & Other)
  {
    id: '19',
    name: 'Arancini',
    description: 'Crispy fried rice balls filled with mozzarella, served with marinara sauce',
    price: 1400,
    category: 'starters',
    subcategory: 'vegetarian',
    image: '/public/assets/menu/Arancini.jpg',
    available: true,
    eta: 45,
  },
  {
    id: '20',
    name: 'Bruschetta',
    description: 'Toasted bread topped with tomatoes, basil, garlic, and olive oil',
    price: 1200,
    category: 'starters',
    subcategory: 'vegetarian',
    image: '/public/assets/menu/Bruschetta.jpg',
    available: true,
    eta: 55,
  },
  {
    id: '21',
    name: 'Caprese Skewers',
    description: 'Skewers with mozzarella, cherry tomatoes, basil, and balsamic glaze',
    price: 1400,
    category: 'starters',
    subcategory: 'vegetarian',
    image: '/public/assets/menu/Caprese_Skewers.jpg',
    available: true,
    eta: 60,
  },
  {
    id: '22',
    name: 'French Onion Soup',
    description: 'Savory onion soup topped with melted Gruyère cheese and toasted bread',
    price: 1200,
    category: 'starters',
    subcategory: 'vegetarian',
    image: '/public/assets/menu/French_Onion_Soup.jpg',
    available: true,
    eta: 45,
  },
  {
    id: '23',
    name: 'Hummus Platter',
    description: 'Smooth hummus served with pita, olives, and fresh vegetables',
    price: 1200,
    category: 'starters',
    subcategory: 'vegetarian',
    image: '/public/assets/menu/Hummus_Platter.jpg',
    available: true,
    eta: 30,
  },
  {
    id: '24',
    name: 'Spinach and Artichoke Dip',
    description: 'Creamy spinach and artichoke dip with tortilla chips and veggies',
    price: 1500,
    category: 'starters',
    subcategory: 'vegetarian',
    image: '/public/assets/menu/Spinach_and_Artichoke_Dip.jpg',
    available: true,
    eta: 75,
  },
  {
    id: '25',
    name: 'Stuffed Mushrooms',
    description: 'Mushrooms stuffed with garlic, cream cheese, and fresh herbs',
    price: 1200,
    category: 'starters',
    subcategory: 'vegetarian',
    image: '/public/assets/menu/Stuffed_Mushrooms.jpg',
    available: true,
    eta: 40,
  },
  {
    id: '26',
    name: 'Sweet Potato Fries',
    description: 'Crispy fried sweet potato fries served with aioli',
    price: 1000,
    category: 'starters',
    subcategory: 'vegetarian',
    image: '/public/assets/menu/Sweet_Potato_Fries.jpg',
    available: true,
    eta: 25,
  },
  {
    id: '27',
    name: 'Vegetable Spring Rolls',
    description: 'Crispy spring rolls filled with vegetables and served with sweet chili sauce',
    price: 1000,
    category: 'starters',
    subcategory: 'vegetarian',
    image: '/public/assets/menu/Vegetable_Spring_Rolls.jpg',
    available: true,
    eta: 50,
  },

  // Main Course (Seafood)
  {
    id: '28',
    name: 'Miso-Glazed Black Cod',
    description: 'Perfectly cooked black cod with a miso glaze, bok choy, and jasmine rice',
    price: 4500,
    category: 'mains',
    subcategory: 'seafood',
    image: '/public/assets/menu/Miso_Glazed_Black_Cod.jpg',
    available: true,
    eta: 95,
  },
  {
    id: '29',
    name: 'Lobster Thermidor',
    description: 'Lobster tail baked in creamy cognac sauce with gratin topping',
    price: 6000,
    category: 'mains',
    subcategory: 'seafood',
    image: '/public/assets/menu/Lobster_Thermidor.jpg',
    available: true,
    eta: 80,
  },
  {
    id: '30',
    name: 'Grilled Salmon',
    description: 'Served with dill butter sauce and roasted seasonal vegetables',
    price: 3800,
    category: 'mains',
    subcategory: 'seafood',
    image: '/public/assets/menu/Grilled_Salmon.jpg',
    available: true,
    eta: 55,
  },
  {
    id: '31',
    name: 'Seared Scallops',
    description: 'Served with cauliflower purée and crispy pancetta',
    price: 4200,
    category: 'mains',
    subcategory: 'seafood',
    image: '/public/assets/menu/Seared_Scallops.jpg',
    available: true,
    eta: 90,
  },
  {
    id: '32',
    name: 'Pan-Fried Sea Bass',
    description: 'With lemon caper sauce and sautéed spinach',
    price: 4000,
    category: 'mains',
    subcategory: 'seafood',
    image: '/public/assets/menu/Pan_Fried_Sea_Bass.jpg',
    available: true,
    eta: 110,
  },
  {
    id: '33',
    name: 'Shrimp Scampi',
    description: 'Garlic butter sauce, fresh linguine, and parsley garnish',
    price: 3500,
    category: 'mains',
    subcategory: 'seafood',
    image: '/public/assets/menu/Shrimp_Scampi.jpg',
    available: true,
    eta: 45,
  },
  {
    id: '34',
    name: 'Tuna Tataki',
    description: 'Lightly seared tuna with sesame crust and ponzu dressing',
    price: 3800,
    category: 'mains',
    subcategory: 'seafood',
    image: '/public/assets/menu/Tuna_Tataki.jpg',
    available: true,
    eta: 75,
  },
  {
    id: '35',
    name: 'Crab Risotto',
    description: 'Creamy Arborio rice with lump crab meat and truffle oil',
    price: 4500,
    category: 'mains',
    subcategory: 'seafood',
    image: '/public/assets/menu/Crab_Risotto.jpg',
    available: true,
    eta: 65,
  },
  {
    id: '36',
    name: 'Seafood Paella',
    description: 'A blend of prawns, mussels, and calamari with saffron rice',
    price: 5000,
    category: 'mains',
    subcategory: 'seafood',
    image: '/public/assets/menu/Seafood_Paella.jpg',
    available: true,
    eta: 120,
  },

  // mains (Meat & Poultry)
  {
    id: '37',
    name: 'Wagyu Beef Tenderloin',
    description: 'Japanese A5 Wagyu, truffle mashed potatoes, and red wine reduction',
    price: 12000,
    category: 'mains',
    subcategory: 'meat & poultry',
    image: '/public/assets/menu/Wagyu_Beef_Tenderloin.jpg',
    available: true,
    eta: 70
  },
  {
    id: '38',
    name: 'Herb-Crusted Rack of Lamb',
    description: 'With Dijon mustard, roasted root vegetables, and mint jus',
    price: 7000,
    category: 'mains',
    subcategory: 'meat & poultry',
    image: '/public/assets/menu/Herb_Crusted_Rack_of_Lamb.jpg',
    available: true,
    eta: 55
  },
  {
    id: '39',
    name: 'Duck Confit',
    description: 'Crispy duck leg with red wine reduction and potato purée',
    price: 6000,
    category: 'mains',
    subcategory: 'meat & poultry',
    image: '/public/assets/menu/Duck_Confit.jpg',
    available: true,
    eta: 80
  },
  {
    id: '40',
    name: 'Roasted Chicken Supreme',
    description: 'Juicy chicken breast with thyme jus and roasted baby potatoes',
    price: 3800,
    category: 'mains',
    subcategory: 'meat & poultry',
    image: '/public/assets/menu/Roasted_Chicken_Supreme.jpg',
    available: true,
    eta: 65
  },
  {
    id: '41',
    name: 'Slow-Cooked Short Ribs',
    description: 'Braised in red wine, served with creamy polenta',
    price: 4500,
    category: 'mains',
    subcategory: 'meat & poultry',
    image: '/public/assets/menu/Slow_Cooked_Short_Ribs.jpg',
    available: true,
    eta: 90
  },
  {
    id: '42',
    name: 'Grilled Ribeye Steak',
    description: 'Charred to perfection with peppercorn sauce and fries',
    price: 5000,
    category: 'mains',
    subcategory: 'meat & poultry',
    image: '/public/assets/menu/Grilled_Ribeye_Steak.jpg',
    available: true,
    eta: 50
  },
  {
    id: '43',
    name: 'Veal Milanese',
    description: 'Breaded veal cutlet served with arugula salad',
    price: 4800,
    category: 'mains',
    subcategory: 'meat & poultry',
    image: '/public/assets/menu/Veal_Milanese.jpg',
    available: true,
    eta: 75
  },
  {
    id: '44',
    name: 'Lamb Shank',
    description: 'Braised lamb with red wine, tomatoes, and rosemary jus',
    price: 5500,
    category: 'mains',
    subcategory: 'meat & poultry',
    image: '/public/assets/menu/Lamb_Shank.jpg',
    available: true,
    eta: 60
  },
  {
    id: '45',
    name: 'Beef Wellington',
    description: 'Puff pastry-wrapped beef with mushroom duxelles and red wine sauce',
    price: 8000,
    category: 'mains',
    subcategory: 'meat & poultry',
    image: '/public/assets/menu/Beef_Wellington.jpg',
    available: true,
    eta: 100
  },

  // mains (Vegetarian & Vegan)
  {
    id: '46',
    name: 'Risotto al Tartufo',
    description: 'Creamy truffle risotto with wild mushrooms and Parmesan shavings',
    price: 2800,
    category: 'mains',
    subcategory: 'vegetarian & vegan',
    image: '/public/assets/menu/Risotto_al_Tartufo.jpg',
    available: true,
    eta: 85
  },
  {
    id: '47',
    name: 'Pasta Primavera',
    description: 'Fresh pasta with seasonal vegetables, olive oil, and Parmesan',
    price: 2200,
    category: 'mains',
    subcategory: 'vegetarian & vegan',
    image: '/public/assets/menu/Pasta_Primavera.jpg',
    available: true,
    eta: 45
  },
  {
    id: '48',
    name: 'Stuffed Bell Peppers',
    description: 'Filled with quinoa, lentils, and spiced tomato sauce',
    price: 2500,
    category: 'mains',
    subcategory: 'vegetarian & vegan',
    image: '/public/assets/menu/Stuffed_Bell_Peppers.jpg',
    available: true,
    eta: 60
  },
  {
    id: '49',
    name: 'Eggplant Parmigiana',
    description: 'Layers of eggplant, marinara, and mozzarella cheese',
    price: 2300,
    category: 'mains',
    subcategory: 'vegetarian & vegan',
    image: '/public/assets/menu/Eggplant_Parmigiana.jpg',
    available: true,
    eta: 50
  },
  {
    id: '50',
    name: 'Vegetarian Pad Thai',
    description: 'Stir-fried rice noodles with tofu, tamarind sauce, and peanuts',
    price: 2700,
    category: 'mains',
    subcategory: 'vegetarian & vegan',
    image: '/public/assets/menu/Vegetarian_Pad_Thai.jpg',
    available: true,
    eta: 40
  },
  {
    id: '51',
    name: 'Wild Mushroom Stroganoff',
    description: 'Creamy mushroom sauce over egg noodles',
    price: 2800,
    category: 'mains',
    subcategory: 'vegetarian & vegan',
    image: '/public/assets/menu/Wild_Mushroom_Stroganoff.jpg',
    available: true,
    eta: 90
  },
  {
    id: '52',
    name: 'Grilled Vegetable Platter',
    description: 'Seasonal vegetables with balsamic glaze',
    price: 1800,
    category: 'mains',
    subcategory: 'vegetarian & vegan',
    image: '/public/assets/menu/Grilled_Vegetable_Platter.jpg',
    available: true,
    eta: 50
  },
  {
    id: '53',
    name: 'Vegan Shepherd\'s Pie',
    description: 'Lentil and vegetable filling topped with mashed sweet potatoes',
    price: 2400,
    category: 'mains',
    subcategory: 'vegetarian & vegan',
    image: '/public/assets/menu/Vegan_Shepherds_Pie.jpg',
    available: true,
    eta: 65
  },
  {
    id: '54',
    name: 'Chickpea and Spinach Curry',
    description: 'Served with basmati rice and naan',
    price: 2200,
    category: 'mains',
    subcategory: 'vegetarian & vegan',
    image: '/public/assets/menu/Chickpea_and_Spinach_Curry.jpg',
    available: true,
    eta: 80
  },

  // Desserts (Cakes & Pastries)
  {
    id: '55',
    name: 'Gold Leaf Chocolate Fondant',
    description: 'Decadent molten chocolate cake with gold leaf garnish and vanilla bean ice cream',
    price: 2500,
    category: 'desserts',
    subcategory: 'cakes & pastries',
    image: '/public/assets/menu/Gold_Leaf_Chocolate_Fondant.jpg',
    available: true,
    eta: 55
  },
  {
    id: '56',
    name: 'Seasonal Fruit Tart',
    description: 'Fresh fruits on an almond pastry with mascarpone cream',
    price: 2200,
    category: 'desserts',
    subcategory: 'cakes & pastries',
    image: '/public/assets/menu/Seasonal_Fruit_Tart.jpg',
    available: true,
    eta: 45
  },
  {
    id: '57',
    name: 'Tiramisu',
    description: 'Classic Italian dessert with espresso-soaked ladyfingers and mascarpone',
    price: 1800,
    category: 'desserts',
    subcategory: 'cakes & pastries',
    image: '/public/assets/menu/Tiramisu.jpg',
    available: true,
    eta: 70
  },
  {
    id: '58',
    name: 'Opera Cake',
    description: 'Layers of almond sponge, coffee buttercream, and ganache',
    price: 2400,
    category: 'desserts',
    subcategory: 'cakes & pastries',
    image: '/public/assets/menu/Opera_Cake.jpg',
    available: true,
    eta: 60
  },
  {
    id: '59',
    name: 'Red Velvet Cheesecake',
    description: 'A creamy twist on the classic red velvet cake',
    price: 2700,
    category: 'desserts',
    subcategory: 'cakes & pastries',
    image: '/public/assets/menu/Red_Velvet_Cheesecake.jpg',
    available: true,
    eta: 50
  },
  {
    id: '60',
    name: 'Croissant Bread Pudding',
    description: 'Warm croissant-based dessert with vanilla sauce',
    price: 2000,
    category: 'desserts',
    subcategory: 'cakes & pastries',
    image: '/public/assets/menu/Croissant_Bread_Pudding.jpg',
    available: true,
    eta: 75
  },
  {
    id: '61',
    name: 'Carrot Cake',
    description: 'Moist spiced cake with cream cheese frosting and walnut topping',
    price: 1800,
    category: 'desserts',
    subcategory: 'cakes & pastries',
    image: '/public/assets/menu/Carrot_Cake.jpg',
    available: true,
    eta: 40
  },
  {
    id: '62',
    name: 'Black Forest Gateau',
    description: 'Chocolate cake layered with cherries and whipped cream',
    price: 2500,
    category: 'desserts',
    subcategory: 'cakes & pastries',
    image: '/public/assets/menu/Black_Forest_Gateau.jpg',
    available: true,
    eta: 80,
  },
  {
    id: '63',
    name: 'Pineapple Upside-Down Cake',
    description: 'Caramelized pineapple topping with a moist sponge base',
    price: 2100,
    category: 'desserts',
    subcategory: 'cakes & pastries',
    image: '/public/assets/menu/Pineapple_Upside_Down_Cake.jpg',
    available: true,
    eta: 65,
  },

  // Desserts (Creamy & Custard-Based)
  {
    id: '64',
    name: 'Crème Brûlée Trio',
    description: 'Vanilla, matcha, and lavender flavors',
    price: 2200,
    category: 'desserts',
    subcategory: 'creamy & custard-based',
    image: '/public/assets/menu/Creme_Brulee_Trio.jpg',
    available: true,
    eta: 72,
  },
  {
    id: '65',
    name: 'Panna Cotta',
    description: 'Silky smooth cream pudding served with a berry compote',
    price: 1900,
    category: 'desserts',
    subcategory: 'creamy & custard-based',
    image: '/public/assets/menu/Panna_Cotta.jpg',
    available: true,
    eta: 90,
  },
  {
    id: '66',
    name: 'Sticky Toffee Pudding',
    description: 'Rich sponge cake with toffee sauce and vanilla ice cream',
    price: 2100,
    category: 'desserts',
    subcategory: 'creamy & custard-based',
    image: '/public/assets/menu/Sticky_Toffee_Pudding.jpg',
    available: true,
    eta: 75,
  },
  {
    id: '67',
    name: 'Rice Pudding',
    description: 'Creamy rice pudding infused with vanilla and cinnamon',
    price: 1600,
    category: 'desserts',
    subcategory: 'creamy & custard-based',
    image: '/public/assets/menu/Rice_Pudding.jpg',
    available: true,
    eta: 85,
  },
  {
    id: '68',
    name: 'Chocolate Mousse',
    description: 'Decadent whipped chocolate with a hint of espresso',
    price: 1800,
    category: 'desserts',
    subcategory: 'creamy & custard-based',
    image: '/public/assets/menu/Chocolate_Mousse.jpg',
    available: true,
    eta: 60,
  },
  {
    id: '69',
    name: 'Flan de Caramel',
    description: 'Smooth caramel custard with a glossy finish',
    price: 1600,
    category: 'desserts',
    subcategory: 'creamy & custard-based',
    image: '/public/assets/menu/Flan_de_Caramel.jpg',
    available: true,
    eta: 90,
  },
  {
    id: '70',
    name: 'Banoffee Pie',
    description: 'Layers of banana, toffee, and whipped cream on a biscuit base',
    price: 2100,
    category: 'desserts',
    subcategory: 'creamy & custard-based',
    image: '/public/assets/menu/Banoffee_Pie.jpg',
    available: true,
    eta: 70,
  },
  {
    id: '71',
    name: 'Parfait',
    description: 'Layers of yogurt, granola, and fresh fruit',
    price: 1500,
    category: 'desserts',
    subcategory: 'creamy & custard-based',
    image: '/public/assets/menu/Parfait.jpg',
    available: true,
    eta: 78,
  },
  {
    id: '72',
    name: 'Mango Kulfi',
    description: 'Traditional Indian mango ice cream with cardamom',
    price: 2000,
    category: 'desserts',
    subcategory: 'creamy & custard-based',
    image: '/public/assets/menu/Mango_Kulfi.jpg',
    available: true,
    eta: 82,
  },

  // Desserts (Frozen & Fruity)
  {
    id: '73',
    name: 'Sorbet Trio',
    description: 'Mango, raspberry, and lemon sorbets',
    price: 1700,
    category: 'desserts',
    subcategory: 'frozen & fruity',
    image: '/public/assets/menu/Sorbet_Trio.jpg',
    available: true,
    eta: 65,
  },
  {
    id: '74',
    name: 'Classic Tartufo',
    description: 'Chocolate and hazelnut gelato with a cherry center',
    price: 2000,
    category: 'desserts',
    subcategory: 'frozen & fruity',
    image: '/public/assets/menu/Classic_Tartufo.jpg',
    available: true,
    eta: 80,
  },
  {
    id: '75',
    name: 'Lemon Meringue Pie',
    description: 'Zesty lemon curd with a fluffy meringue topping',
    price: 2100,
    category: 'desserts',
    subcategory: 'frozen & fruity',
    image: '/public/assets/menu/Lemon_Meringue_Pie.jpg',
    available: true,
    eta: 85,
  },
  {
    id: '76',
    name: 'Tropical Pavlova',
    description: 'Meringue topped with whipped cream and tropical fruits',
    price: 2300,
    category: 'desserts',
    subcategory: 'frozen & fruity',
    image: '/public/assets/menu/Tropical_Pavlova.jpg',
    available: true,
    eta: 70,
  },
  {
    id: '77',
    name: 'Peach Melba',
    description: 'Poached peaches with raspberry sauce and vanilla ice cream',
    price: 2100,
    category: 'desserts',
    subcategory: 'frozen & fruity',
    image: '/public/assets/menu/Peach_Melba.jpg',
    available: true,
    eta: 75,
  },
  {
    id: '78',
    name: 'Mixed Berry Cobbler',
    description: 'Warm berry filling with a biscuit topping and ice cream',
    price: 2200,
    category: 'desserts',
    subcategory: 'frozen & fruity',
    image: '/public/assets/menu/Mixed_Berry_Cobbler.jpg',
    available: true,
    eta: 68,
  },
  {
    id: '79',
    name: 'Frozen Yogurt Sundae',
    description: 'Topped with granola, honey, and seasonal berries',
    price: 1800,
    category: 'desserts',
    subcategory: 'frozen & fruity',
    image: '/public/assets/menu/Frozen_Yogurt_Sundae.jpg',
    available: true,
    eta: 77,
  },
  {
    id: '80',
    name: 'Strawberry Shortcake',
    description: 'Layers of sponge cake, cream, and fresh strawberries',
    price: 2100,
    category: 'desserts',
    subcategory: 'frozen & fruity',
    image: '/public/assets/menu/Strawberry_Shortcake.jpg',
    available: true,
    eta: 82,
  },
  {
    id: '81',
    name: 'Affogato',
    description: 'Vanilla gelato topped with a shot of espresso',
    price: 1800,
    category: 'desserts',
    subcategory: 'frozen & fruity',
    image: '/public/assets/menu/Affogato.jpg',
    available: true,
    eta:64,
  },

// Drinks (Alcoholic Beverages)
{
  id: '82',
  name: 'Dom Pérignon',
  description: 'Premium Champagne known for its elegance and finesse.',
  price: 12000,
  category: 'drinks',
  subcategory: 'alcoholic beverages',
  image: '/public/assets/menu/Dom_Perignon.jpg',
  available: true,
  eta: 72,
},
{
  id: '83',
  name: 'Veuve Clicquot Rosé',
  description: 'Crisp and refreshing sparkling wine with berry notes.',
  price: 10000,
  category: 'drinks',
  subcategory: 'alcoholic beverages',
  image: '/public/assets/menu/Veuve_Clicquot_Rose.jpg',
  available: true,
  eta: 68,
},
{
  id: '84',
  name: 'Château Margaux',
  description: 'A luxurious, full-bodied red wine.',
  price: 15000,
  category: 'drinks',
  subcategory: 'alcoholic beverages',
  image: '/public/assets/menu/Chateau_Margaux.jpg',
  available: true,
  eta: 78,
},
{
  id: '85',
  name: 'Opus One',
  description: 'Rich, velvety Napa Valley Cabernet Sauvignon blend.',
  price: 20000,
  category: 'drinks',
  subcategory: 'alcoholic beverages',
  image: '/public/assets/menu/Opus_One.jpg',
  available: true,
  eta: 65,
},
{
  id: '86',
  name: 'Puligny-Montrachet',
  description: 'Classic white Burgundy with hints of citrus and oak.',
  price: 13000,
  category: 'drinks',
  subcategory: 'alcoholic beverages',
  image: '/public/assets/menu/Puligny_Montrachet.jpg',
  available: true,
  eta: 74,
},
{
  id: '87',
  name: 'Cloudy Bay Sauvignon Blanc',
  description: 'New Zealand white wine with tropical flavors.',
  price: 8000,
  category: 'drinks',
  subcategory: 'alcoholic beverages',
  image: '/public/assets/menu/Cloudy_Bay_Sauvignon_Blanc.jpg',
  available: true,
  eta: 70,
},
{
  id: '88',
  name: 'The Royale',
  description: 'Champagne, elderflower liqueur, and edible gold flakes.',
  price: 6000,
  category: 'drinks',
  subcategory: 'alcoholic beverages',
  image: '/public/assets/menu/The_Royale.jpg',
  available: true,
  eta: 80,
},
{
  id: '89',
  name: 'Midnight Martini',
  description: 'Espresso, vanilla vodka, and chocolate liqueur.',
  price: 4000,
  category: 'drinks',
  subcategory: 'alcoholic beverages',
  image: '/public/assets/menu/Midnight_Martini.jpg',
  available: true,
  eta: 66,
},
{
  id: '90',
  name: 'Classic Margarita',
  description: 'Tequila, lime juice, and triple sec served on the rocks.',
  price: 3000,
  category: 'drinks',
  subcategory: 'alcoholic beverages',
  image: '/public/assets/menu/Classic_Margarita.jpg',
  available: true,
  eta: 72,
},

// Drinks (Non-Alcoholic Beverages)
{
  id: '91',
  name: 'Sparkling Elderflower Tonic',
  description: 'Refreshing blend of elderflower and sparkling water.',
  price: 1500,
  category: 'drinks',
  subcategory: 'non-alcoholic beverages',
  image: '/public/assets/menu/Sparkling_Elderflower_Tonic.jpg',
  available: true,
  eta: 75,
},
{
  id: '92',
  name: 'Custom Mocktails',
  description: 'Tailored non-alcoholic drinks with seasonal flavors.',
  price: 1800,
  category: 'drinks',
  subcategory: 'non-alcoholic beverages',
  image: '/public/assets/menu/Custom_Mocktails.jpg',
  available: true,
  eta: 68,
},
{
  id: '93',
  name: 'Freshly Pressed Juices',
  description: 'Choose from orange, apple, carrot, or green blends.',
  price: 1200,
  category: 'drinks',
  subcategory: 'non-alcoholic beverages',
  image: '/public/assets/menu/Freshly_Pressed_Juices.jpg',
  available: true,
  eta: 77,
},
{
  id: '94',
  name: 'Iced Matcha Latte',
  description: 'Creamy matcha over ice with a touch of vanilla.',
  price: 1500,
  category: 'drinks',
  subcategory: 'non-alcoholic beverages',
  image: '/public/assets/menu/Iced_Matcha_Latte.jpg',
  available: true,
  eta: 70,
},
{
  id: '95',
  name: 'Virgin Mojito',
  description: 'Mint, lime, and soda water for a tropical treat.',
  price: 1300,
  category: 'drinks',
  subcategory: 'non-alcoholic beverages',
  image: '/public/assets/menu/Virgin_Mojito.jpg',
  available: true,
  eta: 79,
},
{
  id: '96',
  name: 'Berry Lemonade',
  description: 'Mixed berries blended with lemon and a touch of honey.',
  price: 1400,
  category: 'drinks',
  subcategory: 'non-alcoholic beverages',
  image: '/public/assets/menu/Berry_Lemonade.jpg',
  available: true,
  eta: 80,
},
{
  id: '97',
  name: 'Cucumber Cooler',
  description: 'Refreshing cucumber, lime, and soda.',
  price: 1200,
  category: 'drinks',
  subcategory: 'non-alcoholic beverages',
  image: '/public/assets/menu/Cucumber_Cooler.jpg',
  available: true,
  eta: 65,
},
{
  id: '98',
  name: 'Chilled Mango Lassi',
  description: 'Smooth mango yogurt drink.',
  price: 1500,
  category: 'drinks',
  subcategory: 'non-alcoholic beverages',
  image: '/public/assets/menu/Chilled_Mango_Lassi.jpg',
  available: true,
  eta: 72,
},
{
  id: '99',
  name: 'Herbal Iced Tea',
  description: 'Infused with chamomile, hibiscus, or mint.',
  price: 1100,
  category: 'drinks',
  subcategory: 'non-alcoholic beverages',
  image: '/public/assets/menu/Herbal_Iced_Tea.jpg',
  available: true,
  eta: 69,
},

// Drinks (Hot Beverages)
{
  id: '100',
  name: 'Espresso',
  description: 'Bold and rich single shot of coffee.',
  price: 800,
  category: 'drinks',
  subcategory: 'hot beverages',
  image: '/public/assets/menu/Espresso.jpg',
  available: true,
  eta: 73,
},
{
  id: '101',
  name: 'Cappuccino',
  description: 'Espresso with steamed milk and frothy foam.',
  price: 1000,
  category: 'drinks',
  subcategory: 'hot beverages',
  image: '/public/assets/menu/Cappuccino.jpg',
  available: true,
  eta: 74,
},
{
  id: '102',
  name: 'Hot Chocolate',
  description: 'Creamy chocolate drink topped with whipped cream.',
  price: 1200,
  category: 'drinks',
  subcategory: 'hot beverages',
  image: '/public/assets/menu/Hot_Chocolate.jpg',
  available: true,
  eta: 65,
},
{
  id: '103',
  name: 'Masala Chai',
  description: 'Spiced Indian tea made with milk and aromatic spices.',
  price: 900,
  category: 'drinks',
  subcategory: 'hot beverages',
  image: '/public/assets/menu/Masala_Chai.jpg',
  available: true,
  eta: 78,
},
{
  id: '104',
  name: 'Matcha Green Tea',
  description: 'Whisked Japanese powdered green tea.',
  price: 1000,
  category: 'drinks',
  subcategory: 'hot beverages',
  image: '/public/assets/menu/Matcha_Green_Tea.jpg',
  available: true,
  eta: 70,
},
{
  id: '105',
  name: 'Americano',
  description: 'Espresso diluted with hot water for a smooth finish.',
  price: 800,
  category: 'drinks',
  subcategory: 'hot beverages',
  image: '/public/assets/menu/Americano.jpg',
  available: true,
  eta: 79,
},
{
  id: '106',
  name: 'Peppermint Tea',
  description: 'Herbal tea with refreshing mint flavor.',
  price: 700,
  category: 'drinks',
  subcategory: 'hot beverages',
  image: '/public/assets/menu/Peppermint_Tea.jpg',
  available: true,
  eta: 75,
},
{
  id: '107',
  name: 'Earl Grey Tea',
  description: 'Black tea infused with bergamot for a citrusy aroma.',
  price: 800,
  category: 'drinks',
  subcategory: 'hot beverages',
  image: '/public/assets/menu/Earl_Grey_Tea.jpg',
  available: true,
  eta: 74,
},
{
  id: '108',
  name: 'Turmeric Latte',
  description: 'Golden milk with as blend of turmeric and spices.',
  price: 1000,
  category: 'drinks',
  subcategory: 'hot beverages',
  image: '/public/assets/menu/Turmeric_Latte.jpg',
  available: true,
  eta: 80,
},
];

export default menuItems;




